### ISSUE TITLE
Incorrect DER encoding of "Named bit lists"

### ISSUE THREAD

**Issue by joernheissler** [wbond/asn1crypto#21]
Hello,
I loaded an x509.Certificate and dumped it again with force=True.
The result differs from the original.
The certificate includes the Extension "Key Usage".
The value is encoded as "03 02 05 a0" in the original, but "03 03 07 a0 00" in the dumped form.
The former is the bit string "101", the latter is "101000000". According to the standards, only the former is correct.

RFC5280 specifies that trailing zeros are removed:
> Named bit lists are BIT STRINGs where the values have been assigned
> names.  This specification makes use of named bit lists in the
> definitions for the key usage, CRL distribution points, and freshest
> CRL certificate extensions, as well as the freshest CRL and issuing
> distribution point CRL extensions.  When DER encoding a named bit
> list, trailing zeros MUST be omitted.  That is, the encoded value
> ends with the last named bit that is set to one.

Also see X.690 11.2.2 and X.680 21.7

**Comment by wbond** [comment]
Thanks for bringing this to my attention.

I found this thread: https://www.ietf.org/mail-archive/web/pkix/current/msg10439.html, which may be of interest to others in the future in regards to DER encoding of bit strings.

**Comment by wbond** [comment]
This should be resolved by 38a2985cb1a7225acd62d32a16a2fb31c178d03f

**Comment by joernheissler** [comment]
Thanks for the quick fix and the two links, interesting reading.
My use case works now, but I think one corner case is still incorrect:
"NOTE 2 – If a bitstring value has no 1 bits, then an encoder shall encode the value with a length of 1 and an initial octet set to 0."
Of course one could argue that a Key with a KeyUsage of ∅ would be useless :-)

**Comment by wbond** [comment]
I did implement that note as I understood it.  I presumed a length of 1 indicates the number of bits, so I encode it as `\x03\x02\x07\x00`. Did you interpret it another way? I tried searching for discussion online, but didn't find anything.

**Comment by joernheissler** [comment]
Length would be the DER length, i.e. 2nd byte of encoding after the tag.
Initial octet is the number of unused bits. It should be in X.690 bitstring.
Gotta run now.

**Comment by wbond** [comment]
I see, so you are suggesting `\x03\x01\x00`?

**Comment by joernheissler** [comment]
Yep, that's right.
But "dumpasn1" shows: "Error: BIT STRING has invalid length 1."
I assume that dumpasn1 is wrong with this regard.

"If the bitstring is empty, there shall be no subsequent octets, and the initial octet shall be zero."
"The initial octet ... The number shall be in the range zero to seven."

**Comment by wbond** [comment]
Perfect, thanks for the extra details. de9e492a1a563af606ebc3ae5e39c2454cbac1b8 should correct this. I'll be releasing 0.18.3 shortly.
